


#' @title Initialize prior for wavelet multivariate regression
#'
#' @description generate list of object corresponding to the parameters of the prior set for analysis
#'
#' @param tens_marg a list of tensor of marginal association generated by \code{cal_Bhat_Shat_tensor}
#'
#' @param indx_list List generated by \code{\link{gen_wavelet_indx}}   for the given level of resolution
#'
#' @param data.driven logical, if TRUE use data driven covariance matrix procedure for fitting mash otherwise uses  cov_canonical method mashr. Set as TRUE by default
#'
#' @return a list of mash objects
init_prior_mvfsusie <- function( tens_marg,indx_list, data.driven=TRUE, verbose=FALSE)
{


  G_prior <- lapply(  1: (log2(sum( lengths(indx_lst)))+1) , function(s) fit_mash_level(tens_marg, s, indx_lst, data.driven =data.driven, verbose=verbose))
  class(G_prior) <- "mash_per_scale"
  return(G_prior)
}

#' @title Access to list of the prior covariances
#'
#' @description Access to list of fitted covariance of a mash prior of a given scale
#'
#' @param G_prior prior generated by \code{init_prior_mvfsusie}
#'
#' @param s scale of interest
#'
#' @return a list of covariance matrices
get_Ulist  <- function( G_prior,s)
{
  out <-  G_prior[[s]]$fitted_g$Ulist
  return( out)
}



#' @title Access to the scale grid of the mash prior
#'
#' @description Access to the scale grid of the mash prior
#'
#' @param G_prior prior generated by \code{init_prior_mvfsusie}
#'
#' @param s scale of interest
#'
#' @return a vector of scaling factor

get_grid <- function(G_prior,s)
{
  out <- G_prior[[s]]$fitted_g$grid
  return(out)
}



#' @title Access to the scale grid of the mash prior
#'
#' @description Access to the scale grid of the mash prior
#'
#' @param G_prior prior generated by \code{init_prior_mvfsusie}
#'
#' @param s scale of interest
#'
#' @return a vector of scaling factor

update_prior_weight_mvfsusie <- function(G_prior,tpi_k)
{
  out <- mapply(update_mash_pi ,G_prior, tpi_k, SIMPLIFY = FALSE)
  class(out) <- "mash_per_scale"
  return(out)
}




#' @title Update mash object mixture proportion
#'
#' @description Update mash object mixture proportion
#'
#' @param G a mash object
#'
#' @param tpi a vector of proportion
#'
#' @return a mash object with updated mixture proportion
#'
#' @export



update_mash_pi<- function(G , tpi)
{

  if( length(G$fitted_g$pi )==length(tpi))
  {
    G$fitted_g$pi <- tpi
  }else{
    stop("Error: when updating ash object length of new mixture proportion
    \nlonger than the mixture proportion in the ash object    ")

  }

  return(G)
}



#' @title Get mixture proportion for scale mash prior
#'
#' @description  Get mixture proportion for scale mash prior
#'
#' @param G_prior  a prior generated by  \code{\link{init_prior_mvfsusie}} mash object
#'
#'
#' @return a list of mixture proportion
#'
#' @export


get_pi_G_prior.mash_per_scale <- function(G_prior)
{
  out <- lapply( 1: length(G_prior), function(s) G_prior[[s]]$fitted_g$pi)
  return(out)
}



#' @title Get mixture proportion for mash per scale prior
#'
#' @description Get mixture proportion for mash per scale prior
#'
#' @param G_prior  mash per scale prior
#'
#' @return list of  mixture proportion
#'

get_pi_G_prior <- function(G_prior, ...)
  UseMethod("get_pi_G_prior")





#' @title Update mixture proportion for mixture normal prior
#'
#' @description Add description here.
#'
#' @param G_prior a prior of class "mixture_normal" or a prior of class "mixture_normal_per_scale"
#'
#' @param tpi a vector of proportion of class "pi_mixture_normal" resp "pi_mixture_normal_per_scale"
#'
#' @return a prior of class "mixture_normal" or a prior of class "mixture_normal_per_scale"
#'
#' @export
#'
#'

update_prior <- function(G_prior, tpi, ...)
  UseMethod("update_prior")


#' @rdname update_prior
#'
#' @method update_prior mash_per_scale
#'
#' @export update_prior.mash_per_scale
#'
#' @export
#'
update_prior.mash_per_scale <- function(G_prior, tpi, ...)
{

    out <- mapply(update_mash_pi ,G_prior, tpi, SIMPLIFY = FALSE)
    class(out) <- "mixture_normal_per_scale"

  return(G_prior)
}

