.mvf_log_mean_exp <- function(x) {
  max_x <- max(x)
  if (is.infinite(max_x) && max_x < 0) {
    return(-Inf)
  }
  max_x + log(mean(exp(x - max_x)))
}

#' @title Compute KL divergence effect l
#
#' @param multfsusie.obj a susisF object defined by init_multfsusie_obj function
#
#' @param l integer larger or equal to 1. Corresponds to the effect to be accessed
#
#' @param Y wavelet transformed phenotype
#
#' @param X matrix of covariate
#
#' @param list_indx_lst list generated by gen_wavelet_indx for the given level of resolution
#'
#' @param ind_analysis output of which_notNA_pos
#'
#' @param ... Additional arguments passed to other functions.
#
#' @return The KL divergence for effect l
#' @export
#' @keywords internal
cal_KL_l <- function(multfsusie.obj, l, Y, X,   list_indx_lst,ind_analysis, ...)
  UseMethod("cal_KL_l")




#' @rdname cal_KL_l
#'
#' @method cal_KL_l multfsusie
#'
#' @export cal_KL_l.multfsusie
#'
#' @export
#' @keywords internal

cal_KL_l.multfsusie <- function(multfsusie.obj, l, Y, X, list_indx_lst,ind_analysis, ...)
{
  # q_l is the exact single-effect posterior for the partial residual R_l.
  # Thus KL(q_l || prior_l) is its posterior expected log-likelihood ratio
  # minus the shared-SNP marginal log Bayes factor. This identity includes
  # both the SNP-assignment and modality-specific coefficient-prior terms.
  R_l <- cal_partial_resid(
    multfsusie.obj = multfsusie.obj,
    l = l - 1L,
    X = X,
    Y = Y,
    list_indx_lst = list_indx_lst
  )
  EF <- get_post_F(multfsusie.obj, l)
  EF2 <- get_post_F2(multfsusie.obj, l)
  expected_log_likelihood_ratio <- 0

  if (!is.null(Y$Y_u)) {
    for (k in seq_len(ncol(Y$Y_u))) {
      idx <- ind_analysis$idx_u[[k]]
      X_k <- X[idx, , drop=FALSE]
      expected_log_likelihood_ratio <- expected_log_likelihood_ratio +
        sum(R_l$Y_u[idx, k] * (X_k %*% EF$post_u[, k])) /
          multfsusie.obj$sigma2$sd_u[k] -
        sum(colSums(X_k^2) * EF2$post_u_sd2[, k]) /
          (2 * multfsusie.obj$sigma2$sd_u[k])
    }
  }

  if (!is.null(Y$Y_f)) {
    for (k in seq_along(Y$Y_f)) {
      idx <- ind_analysis$idx_f[[k]]
      X_k <- X[idx, , drop=FALSE]
      expected_log_likelihood_ratio <- expected_log_likelihood_ratio +
        sum(R_l$Y_f[[k]][idx, , drop=FALSE] *
              (X_k %*% EF$post_f[[k]])) /
          multfsusie.obj$sigma2$sd_f[k] -
        sum(colSums(X_k^2) * rowSums(EF2$post_f_sd2[[k]])) /
          (2 * multfsusie.obj$sigma2$sd_f[k])
    }
  }

  lBF <- get_lBF(multfsusie.obj, l)
  log_model_BF <- .mvf_log_mean_exp(lBF)

  expected_log_likelihood_ratio - log_model_BF
}


#' @title Compute log likelihood of single function regression of effect l
#
#' @param multfsusie.obj a multfsusie object defined by init_multfsusie_obj function
#'
#' @param l effect to update
#'
#' @param Y wavelet transformed phenotype
#'
#' @param X Matrix of covariates

#' @param ind_analysis output of which_notNA_pos
#'
#' @param ... Additional arguments passed to other functions.
#'
#' @return The log-likelihood, \eqn{\log p(Y | X, V)}, where V is the prior parameters
#' @export
#' @keywords internal
loglik_SFR <- function    (multfsusie.obj, l, Y ,X,  ...)
  UseMethod("loglik_SFR")




#' @rdname loglik_SFR
#'
#' @method loglik_SFR multfsusie
#'
#' @export loglik_SFR.multfsusie
#'
#' @export
#'
#' @keywords internal

loglik_SFR.multfsusie <- function(multfsusie.obj, l, Y ,X,ind_analysis , ... )
{
  lBF <- get_lBF(multfsusie.obj,l)
  lBF_model <- .mvf_log_mean_exp(lBF)

  sum_over_effect <-  0
  if(!is.null(Y$Y_u)){
    sum_over_effect <- sum_over_effect+Reduce("+", lapply( 1:ncol(Y$Y_u),
                                                           function(k)  sum(stats::dnorm(Y$Y_u[  ind_analysis$idx_u[[k]],k],
                                                                                  0,
                                                                                  sqrt(multfsusie.obj$sigma2$sd_u[k]),
                                                                                  log = TRUE)
                                                           )
    )
    )

  }
  if(!is.null(Y$Y_f)){
    sum_over_effect <- sum_over_effect+Reduce("+", lapply( 1:length(Y$Y_f),
                                                           function(k)  sum(stats::dnorm(Y$Y_f[[k]][  ind_analysis$idx_f[[k]],],
                                                                                  0,
                                                                                  sqrt(multfsusie.obj$sigma2$sd_f[k]),
                                                                                  log = TRUE)
                                                           )
    )
    )
  }

  loglik <- lBF_model + sum_over_effect

  return(loglik)
}


#' @title Compute posterior expected loglikelihood for  single function regression of effect l
#'
#' @param multfsusie.obj a multfsusie object defined by init_multfsusie_obj function
#'
#' @param l effect to update
#'
#' @param Y wavelet transformed phenotype
#'
#' @param X Matrix of covariates
#'
#' @param ind_analysis output of which_notNA_pos
#'
#' @param ... Additional arguments passed to other functions.
#'
#' @return posterior expected loglikelihood for  single function regression of effect l
#' @export
#' @keywords internal
loglik_SFR_post <- function    (multfsusie.obj, l,Y,X, ...)
  UseMethod("loglik_SFR_post")


#' @rdname loglik_SFR_post
#'
#' @method loglik_SFR_post multfsusie
#'
#' @export loglik_SFR_post.multfsusie
#'
#' @export
#' @keywords internal

loglik_SFR_post.multfsusie <- function(multfsusie.obj, l,Y,X, ind_analysis,  ... )
{
  EF  <- get_post_F(multfsusie.obj,l)
  EF2 <- get_post_F2(multfsusie.obj,l)
  s2  <- multfsusie.obj$sigma2
  out <- 0
  if (!is.null(Y$Y_u)) {
    out <- out + sum(vapply(seq_len(ncol(Y$Y_u)), function(k) {
      idx <- ind_analysis$idx_u[[k]]
      X_k <- X[idx, , drop=FALSE]
      y_k <- Y$Y_u[idx, k]
      posterior_mean <- X_k %*% EF$post_u[, k]
      expected_signal_ss <- sum(colSums(X_k^2) * EF2$post_u_sd2[, k])

      -0.5 * length(idx) * log(2 * pi * s2$sd_u[k]) -
        (sum(y_k^2) - 2 * sum(y_k * posterior_mean) +
           expected_signal_ss) / (2 * s2$sd_u[k])
    }, numeric(1)))
  }

  if (!is.null(Y$Y_f)) {
    out <- out + sum(vapply(seq_along(Y$Y_f), function(k) {
      idx <- ind_analysis$idx_f[[k]]
      X_k <- X[idx, , drop=FALSE]
      y_k <- Y$Y_f[[k]][idx, , drop=FALSE]
      posterior_mean <- X_k %*% EF$post_f[[k]]
      expected_signal_ss <- sum(colSums(X_k^2) *
                                  rowSums(EF2$post_f_sd2[[k]]))

      -0.5 * length(idx) * ncol(y_k) * log(2 * pi * s2$sd_f[k]) -
        (sum(y_k^2) - 2 * sum(y_k * posterior_mean) +
           expected_signal_ss) / (2 * s2$sd_f[k])
    }, numeric(1)))
  }

  out
}


#' @title Expected log likelihood for a   multfsusie   object
#'
#' @param multfsusie.obj a multfsusie object defined by init_multfsusie_obj function
#'
#' @param Y Matrix of outcomes
#'
#' @param X Matrix of covariates
#' @param ind_analysis list of indices for the analysis
#' @return Expected log likelihood
#' @export
#' @keywords internal
Eloglik <- function    (multfsusie.obj, Y, X,ind_analysis,  ...)
  UseMethod("Eloglik")


#' @rdname Eloglik
#'
#' @method Eloglik multfsusie
#'
#' @export Eloglik.multfsusie
#' @export
#' @keywords internal
Eloglik.multfsusie <-  function (multfsusie.obj,Y ,X,ind_analysis, ... ) {
  out <- 0
  R2 <- get_ER2( multfsusie.obj, Y, X, ind_analysis=ind_analysis)
  if( !is.null( Y$Y_u)){
    n_col <- ncol(Y$Y_u)
    out <- out + sum(vapply(seq_len(n_col), function(k) {
      n_observed <- length(ind_analysis$idx_u[[k]])
      -(n_observed / 2) * log(2 * pi * multfsusie.obj$sigma2$sd_u[k]) -
        R2$uni[k] / (2 * multfsusie.obj$sigma2$sd_u[k])
    }, numeric(1)))
  }
  if( !is.null(Y$Y_f)){
    out <- out + sum(vapply(seq_along(Y$Y_f), function(k) {
      n_observed <- length(ind_analysis$idx_f[[k]])
      n_coefficients <- ncol(Y$Y_f[[k]])
      -(n_observed * n_coefficients / 2) *
        log(2 * pi * multfsusie.obj$sigma2$sd_f[k]) -
        R2$f[k] / (2 * multfsusie.obj$sigma2$sd_f[k])
    }, numeric(1)))
  }


  return(out)
}

#' @title Get objective function from data and multfsusie object
#'
#' @param multfsusie.obj a multfsusie object defined by init_multfsusie_obj function
#'
#' @param Y Matrix of outcomes
#
#' @param X matrix of covariate
#
#' @param ind_analysis output of which_notNA_pos
#'
#' @param ... Additional arguments passed to other functions.
#'
#' @return objective function value
#
#' @export
#' @keywords internal
get_objective <- function    (multfsusie.obj,  Y, X,  ind_analysis,  ...)
  UseMethod("get_objective")


#' @rdname get_objective
#'
#' @method get_objective multfsusie
#'
#' @export get_objective.multfsusie
#' @export
#' @keywords internal
get_objective.multfsusie <- function    (multfsusie.obj, Y, X  ,ind_analysis, ...)
{
  Eloglik(multfsusie.obj, Y, X, ind_analysis=ind_analysis) -
    sum(multfsusie.obj$KL)

}
