





#' @title Compute KL divergence effect l
#
#' @param multfsusie.obj a susisF object defined by \code{\link{init_multfsusie_obj}} function
#
#' @param l integer larger or equal to 1. Corresponds to the effect to be accessed
#
#' @param Y wavelet transformed phenotype
#
#' @param X matrix of covariate
#
#' @param list_indx_lst list generated by gen_wavelet_indx for the given level of resolution
#
#' @return The KL divergence for effect l
#' @export
#' @keywords internal
cal_KL_l <- function(multfsusie.obj, l, Y, X, D,C , list_indx_lst,ind_analysis, ...)
  UseMethod("cal_KL_l")




#' @rdname cal_KL_l
#'
#' @method cal_KL_l multfsusie
#'
#' @export cal_KL_l.multfsusie
#'
#' @export
#' @keywords internal

cal_KL_l.multfsusie <- function(multfsusie.obj, l, Y, X, list_indx_lst,ind_analysis, ...)
{


  R_l <- cal_partial_resid(
                           multfsusie.obj = multfsusie.obj,
                                l         =  (l-1),
                                X         =  X,
                                Y         =  Y,
                          list_indx_lst   =  list_indx_lst
  )



  out <-  - loglik_SFR(multfsusie.obj, l,Y,X,ind_analysis=ind_analysis)- loglik_SFR_post(multfsusie.obj, l,R_l,X,ind_analysis=ind_analysis)
  return(out)
}


#' @title Compute log likelihood of single function regression of effect l
#
#' @param multfsusie.obj a multfsusie object defined by \code{\link{init_multfsusie_obj}} function
#'
#' @param l effect to update
#'
#' @param Y wavelet transformed phenotype
#'
#' @param X Matrix of covariates
#'
#' @return The log-likelihood, \eqn{\log p(Y | X, V)}, where V is the prior parameters
#' @export
#' @keywords internal
loglik_SFR <- function    (multfsusie.obj, l,  ...)
  UseMethod("loglik_SFR")




#' @rdname loglik_SFR
#'
#' @method loglik_SFR multfsusie
#'
#' @export loglik_SFR.multfsusie
#'
#' @export
#' @keywords internal

loglik_SFR.multfsusie <- function(multfsusie.obj, l,Y ,X,ind_analysis=ind_analysis )
{
  lBF <- get_lBF(multfsusie.obj,l)
  prior_weights <- rep(1/ncol(X),ncol(X))
  maxlBF <- max(lBF)
  w = exp( lBF- maxlBF)
  w_weighted = w * prior_weights
  weighted_sum_w = sum(w_weighted)

  lBF_model = maxlBF + log(weighted_sum_w)

  sum_over_effect <-  0
  if(!is.null(Y$Y_u)){
    sum_over_effect <- sum_over_effect+Reduce("+", lapply( 1:ncol(Y$Y_u),
                                                           function(k)  sum(dnorm(Y$Y_u[  ind_analysis$idx_u[[k]],k],
                                                                                  0,
                                                                                  sqrt(multfsusie.obj$sigma2$sd_u[k]),
                                                                                  log = TRUE)
                                                           )
    )
    )

  }
  if(!is.null(Y$Y_f)){
    sum_over_effect <- sum_over_effect+Reduce("+", lapply( 1:length(Y$Y_f),
                                                           function(k)  sum(dnorm(Y$Y_f[[k]][  ind_analysis$idx_f[[k]],],
                                                                                  0,
                                                                                  sqrt(multfsusie.obj$sigma2$sd_f[k]),
                                                                                  log = TRUE)
                                                           )
    )
    )
  }

  loglik <- lBF_model + sum_over_effect

  return(loglik)
}


#' @title Compute posterior expected loglikelihood for  single function regression of effect l
#'
#' @param multfsusie.obj a multfsusie object defined by \code{\link{init_multfsusie_obj}} function
#'
#' @param l effect to update
#'
#' @param Y wavelet transformed phenotype
#'
#' @param X Matrix of covariates
#'
#' @return posterior expected loglikelihood for  single function regression of effect l
#' @export
#' @keywords internal
loglik_SFR_post <- function    (multfsusie.obj, l,  ...)
  UseMethod("loglik_SFR_post")


#' @rdname loglik_SFR_post
#'
#' @method loglik_SFR_post multfsusie
#'
#' @export loglik_SFR_post.multfsusie
#'
#' @export
#' @keywords internal

loglik_SFR_post.multfsusie <- function(multfsusie.obj, l,Y,X, ind_analysis )
{

  EF  <- get_post_F(multfsusie.obj,l)
  EF2 <- get_post_F2(multfsusie.obj,l)
  s2  <- multfsusie.obj$sigma2
  out <- 0
  if( !is.null(s2$sd_u))
  {
    n <- nrow(Y$Y_u)
    out <-  Reduce("+",lapply(1: ncol(Y$Y_u),
                              function(k) -0.5*n*log(2*pi*s2$sd_u[k]) - 0.5/s2$sd_u[k]*(sum(Y$Y_u[ind_analysis$idx_u[[k]],k]*Y$Y_u[ind_analysis$idx_u[[k]],k])- 2*sum(Y$Y_u[ind_analysis$idx_u[[k]],k]*X[ind_analysis$idx_u[[k]],]%*%EF$post_uni[,k])+ sum(attr(X,"d") * EF2$post_uni_sd2[,k]))
    )
    )
  }

  if( !is.null(s2$sd_f))
  {

    n <- rep(nrow(Y$Y_f[[1]]), length(Y$Y_f) )
    t <- lapply(1: length(Y$Y_f), function(k) ncol(Y$Y_f[[k]] ) )


    tt <- Reduce("+",lapply(1: length(Y$Y_f),
                            function(k) -0.5*n[k]*t[[k]]*log(2*pi*s2$sd_f[k]) - 0.5/s2$sd_f[k]*(sum(Y$Y_f[[k]][ind_analysis$idx_f[[k]],]*Y$Y_f[[k]][ind_analysis$idx_f[[k]],])- 2*sum(Y$Y_f[[k]][ind_analysis$idx_f[[k]],]*X[ind_analysis$idx_f[[k]],]%*%EF$post_f[[k]])+ sum(attr(X,"d") * EF2$post_f_sd2[[k]]))
    )
    )
    out <- tt + out
  }

  return(out)
}


#' @title Expected log likelihood for a   multfsusie   object
#'
#' @param multfsusie.obj a multfsusie object defined by \code{\link{init_multfsusie_obj}} function
#'
#' @param Y Matrix of outcomes
#'
#' @param X Matrix of covariates
#'
#' @return Expected log likelihood
#' @export
#' @keywords internal
Eloglik <- function    (multfsusie.obj, Y, X,  ...)
  UseMethod("Eloglik")


#' @rdname Eloglik
#'
#' @method Eloglik multfsusie
#'
#' @export Eloglik.multfsusie
#' @export
#' @keywords internal
Eloglik.multfsusie <-  function (multfsusie.obj,Y ,X,ind_analysis ) {
  out <- 0
  R2 <- get_ER2( multfsusie.obj, Y, X, ind_analysis=ind_analysis)
  if( !is.null( Y$Y_u)){
    n = nrow(Y$Y_u)
    n_col <- ncol(Y$Y_u)
    out <- out+   Reduce( "+", lapply( 1: n_col, function( k) -(n/2) * log(2*pi*multfsusie.obj$sigma2$sd_u[k]) - (1/(2*multfsusie.obj$sigma2$sd_u[k])) *R2$uni[k])
    )
  }
  if( !is.null(Y$Y_f)){
    n <- rep(nrow(Y$Y_f[[1]]), length(Y$Y_f) )
    t <- lapply(1: length(Y$Y_f), function(k) ncol(Y$Y_f[[k]] ) )
    tt <- Reduce("+",lapply(1: length(Y$Y_f),
                            function(k) -(n[k]*t[[k]]/2) * log(2*pi*multfsusie.obj$sigma2$sd_f[k]) - (1/(2*multfsusie.obj$sigma2$sd_f[k])) * R2$f[k]
                           )
         )
    out <- out +tt
  }


  return(out)
}

#' @title Get objective function from data and multfsusie object
#'
#' @param multfsusie.obj a multfsusie object defined by \code{\link{init_multfsusie_obj}} function
#'
#' @param Y Matrix of outcomes
#
#' @param X matrix of covariate
#
#' @param D matrix of wavelet D coefficients from the original input data (Y)
#
#' @param C vector of wavelet scaling coefficient from the original input data (Y)
#
#' @param indx_lst list generated by gen_wavelet_indx for the given level of resolution
#
#' @return objective function value
#
#' @export
#' @keywords internal
get_objective <- function    (multfsusie.obj,  Y, X, D, C , indx_lst,  ...)
  UseMethod("get_objective")


#' @rdname get_objective
#'
#' @method get_objective multfsusie
#'
#' @export get_objective.multfsusie
#' @export
#' @keywords internal
get_objective.multfsusie <- function    (multfsusie.obj, Y, X , list_indx_lst,ind_analysis, ...)
{
    out <- Eloglik(multfsusie.obj, Y, X,ind_analysis=ind_analysis) - sum(multfsusie.obj$KL)
  return(out)

}
