
#' @title Initialize a mvfsusie object
#'
#' @param L number of non zero coefficients An L-vector containing the indices of the
#'   nonzero coefficients.
#'
#' @param G_prior prior object defined by init_prior_mvfsusie function
#'
#' @param Y tensor matrix of outcomes
#'
#' @param X Matrix of covariates
#'
#' @return A list with the following elements
#' \item{fitted_wc}{ list of length L, each element contains the fitted wavelet coefficients of effect l}
#' \item{fitted_wc2}{list of length L, each element contains the variance of the fitted wavelet coefficients of effect l}
#' \item{alpha_hist}{ history of the fitted alpha value}
#' \item{N}{ number of indidivual in the study}
#' \item{sigma2}{residual variance}
#' \item{n_wac}{number of wavelet coefficients}
#' \item{ind_fitted_func}{fitted curves of each individual }
#' \item{cs}{credible set}
#' \item{pip}{Posterior inclusion probabilites}
#' \item{G_prior}{a G_prior of the same class as the input G_prior, used for internal calculation}
#' \item{lBF}{ log Bayes factor for the different effect}
#' \item{KL}{ the KL divergence for the different effect}
#' \item{ELBO}{ The evidence lower bound}
#' \item{lfsr_wc}{Local fasle sign rate of the fitted wavelet coefficients}
#'
init_mvfsusie_obj <- function(L, G_prior, Y,X )
{


  fitted_wc       <-  list()
  fitted_wc2      <-  list()
  alpha           <-  list()
  alpha_hist      <-  list()
  ind_fitted_func <-  array(0, dim= c(dim(Y)) )
  cs              <-  list()
  pip             <-  rep(0, dim(X)[2])
  est_pi          <-  list()
  est_sd          <-  list()
  lfsr_wc         <-  list()
  lfsr_func       <-  list()
  L               <-  L
  G_prior         <-  G_prior
  N               <-  dim(Y)[1]
  n_wac           <-  dim(Y)[2]
  n_cond          <-  dim(Y)[3]
  P               <-  dim(X)[2]
  sigma2          <-  1
  lBF             <-  list()
  KL              <-  rep(NA,L)
  ELBO            <-  c()
  for ( l in 1:L )
  {
    fitted_wc[[l]]        <-  array(0, dim= c(dim(X)[2], ncol=dim(Y)[2], dim(Y)[3])  )
    fitted_wc2[[l]]       <-  array(0, dim= c(dim(X)[2], ncol=dim(Y)[2], dim(Y)[3])  )
    alpha [[l]]           <-  rep(0, dim(X)[2])
    cs[[l]]               <-  list()
    est_pi [[l]]          <-  get_pi_G_prior(G_prior)
    lBF[[l]]              <-  rep(NA, ncol(X))
    lfsr_wc[[l]]          <-  rep(1, ncol(Y))
    lfsr_func[[l]]        <-  rep(1, ncol(Y))
  }
  obj <- list( fitted_wc       = fitted_wc,
               fitted_wc2      = fitted_wc2,
               lfsr_wc         = lfsr_wc,
               lBF             = lBF,
               KL              = KL,
               ELBO            = ELBO,
               ind_fitted_func = ind_fitted_func,
               G_prior         = G_prior,
               alpha_hist      = alpha_hist,
               N               = N,
               n_wac           = n_wac,
               sigma2          = sigma2,
               P               = P,
               alpha           = alpha,
               cs              = cs,
               pip             = pip,
               est_pi          = est_pi,
               est_sd          = est_sd,
               L               = L)

  class(obj) <- "mvfsusie"
  return(obj)
}


#'
#'@title Access mvfmvfsusie internal prior
#'
#' @param mvfsusie.obj a mvfsusie object defined by \code{\link{init_mvfsusie_obj}} function
#'
#' @return G_prior a mash_per_scale object
#'
#' @export
#'
#'
get_G_prior  <- function(mvfsusie.obj.obj, ...)
  UseMethod("get_G_prior")


#' @rdname get_G_prior
#'
#' @method get_G_prior mvfsusie
#'
#' @export get_G_prior.mvfsusie
#'
#' @export
#'
get_G_prior.mvfsusie <- function(mvfsusie.obj, ...)
{
  out <- mvfsusie.obj$G_prior
  class(out) <- 'mash_per_scale'
  return(out)
}




#'@title Update  mvfsusie object using the output of EM_pi
#'
#' @param mvfsusie.obj a mvfsusie object defined by \code{\link{init_mvfsusie_obj }} function
#'
#' @param l integer larger or equal to 1. Corresponds to the effect to be accessed
#'
#' @param EM_pi an object of the class "EM_pi" generated by the function \code\link{EM_pi_mvfsusie}}
#'
#' @return mvfsusie object
#'
#' @export

update_mvfsusie  <- function(mvfsusie.obj, l, EM_pi, tens_marg, indx_lst, all=FALSE ,...)
{

  if( l > length(mvfsusie.obj$est_pi))
  {
    stop("Error trying to access mixture proportion")
  }
  if( l < 1)
  {
    stop("Error l should be larger ")
  }
  if(  "EM_pi_mvfsusie"  %!in%  class(EM_pi)  )
  {
    stop("Error EM_pi should be of the class EM_pi_mvfsusie")
  }
  mvfsusie.obj         <-   update_pi( mvfsusie.obj =  mvfsusie.obj ,
                                      l             = l ,
                                      tpi           =  EM_pi$tpi_k)
  mvfsusie.obj$G_prior    <-   update_prior(get_G_prior(mvfsusie.obj) , EM_pi$tpi_k  )
  post_tens_res <- get_post_tens (G_prior,
                                  tens_marg,
                                  indx_lst,
                                  all = all)

  mvfsusie.obj$fitted_wc[[l]]   <- post_tens_res$post_mean_tens
  mvfsusie.obj$fitted_wc2[[l]]  <- post_tens_res$post_sd_tens

  new_alpha    <- cal_zeta_mvfsusie(  EM_pi$lBF)
  mvfsusie.obj <- update_alpha(mvfsusie.obj, l, new_alpha)
  mvfsusie.obj <- update_lBF(mvfsusie.obj, l, EM_pi$lBF)
  if(all)
  {
    mvfsusie.obj <- update_lfsr (mvfsusie.obj, l, post_tens_res)

  }

  return(mvfsusie.obj)
}


#' @title Update alpha   mvfsusie  mixture proportion of effect l
#'
#' @param mvfsusie.obj a  mvfsusie object defined by \code{\link{init_mvfsusie_obj}} function
#'
#' @param l integer larger or equal to 1. Corresponds to the effect to be accessed
#'
#' @param alpha  vector of p alpha values summing up to one
#'
#' @return  mvfsusie object
#'
#' @export
#'

update_alpha  <-  function(mvfsusie.obj, l, alpha, ... )
  UseMethod("update_alpha")


#' @rdname update_alpha
#'
#' @method update_alpha mvfsusie
#'
#' @export update_alpha.mvfsusie
#'
#' @export
#'
update_alpha.mvfsusie <-  function(mvfsusie.obj, l, alpha, ... )
{
  mvfsusie.obj$alpha[[l]] <- alpha
  mvfsusie.obj$alpha_hist[[ (length(mvfsusie.obj$alpha_hist)+1)  ]] <- alpha
  return( mvfsusie.obj)
}





#' @title Update mixture proportion of mvfsusie mixture proportions of effect l
#'
#' @param mvfsusie.obj a mvfsusie object defined by \code{\link{init_mvfsusie_obj}} function
#'
#' @param l integer larger or equal to 1. Corresponds to the effect to be accessed
#'
#' @param tpi an object of class  "pi_mixture_mash_per_scale"
#'
#' @return mvfsusie object
#'
#' @export

update_pi <- function( mvfsusieF.obj, l, tpi, ...)
  UseMethod("update_pi")

#' @rdname update_pi
#'
#' @method update_pi mvfsusie
#'
#' @export update_pi.mvfsusie
#'
#' @export
#'
update_pi.mvfsusie <- function( mvfsusie.obj, l, tpi, ...)
{

  if( l > length(mvfsusie.obj$est_pi))
  {
    stop("Error trying to access mixture proportion")
  }
  if( l < 1)
  {
    stop("Error l should be larger ")
  }

  mvfsusie.obj$est_pi[[l]] <- tpi
  out <- mvfsusie.obj
  class(out) <- "mvfsusie"
  return(out)
}






#'@title Update mvfsusie log Bayes factor
#'
#'@param mvfsusie.obj a mvfsusie object defined by \code{\link{init_mvfsusie_obj}} function
#'@param l effect to update
#'@param lBF vector of length p, containning the updated log Bayes factors
#'@return mvfsusie object
#'@export

update_lBF  <- function    (mvfsusie.obj, l, lBF, ...)
  UseMethod("update_lBF")

#' @rdname update_lBF
#'
#' @method update_lBF mvfsusie
#'
#' @export update_lBF.mvfsusie
#'
#' @export
#'

update_lBF.mvfsusie <- function    (mvfsusie.obj,l, lBF, ...)
{
  if(l> mvfsusie.obj$L)
  {
    stop("Error: trying to update more effects than the number of specified effect")
  }

  mvfsusie.obj$lBF[[l]] <- lBF
  return(mvfsusie.obj)
}








#'@title Update mvfsusie local False Sign Rate
#'
#'@param mvfsusie.obj a mvfsusie object defined by \code{\link{init_mvfsusie_obj}} function
#'
#'@param l effect to update
#'
#' @param tens_post a object generated with  \code{\link{get_post_tens}} with argument all set to TRUE
#'
#'@return mvfsusie object
#'@export

update_lfsr  <- function    (mvfsusie.obj,l,tens_post ,...)
  UseMethod("update_lfsr")

#' @rdname update_lfsr
#'
#' @method update_lfsr mvfsusie
#'
#' @export update_lfsr.mvfsusie
#'
#' @export
#'

update_lfsr.mvfsusie <- function(mvfsusie.obj,l,post_tens,...)
{
  mvfsusie.obj$lfsr_wc[[l]] <- post_tens$lfsr_tens
  return(mvfsusie.obj)
}




