


#' @title Initialize prior for wavelet multivariate regression
#'
#' @description generate list of object corresponding to the parameters of the prior set for analysis
#'
#' @param tens_marg a list of tensor of marginal association generated by \code{cal_Bhat_Shat_tensor}
#'
#' @param indx_list List generated by \code{\link{gen_wavelet_indx}}   for the given level of resolution
#'
#' @param data.driven logical, if TRUE use data driven covariance matrix procedure for fitting mash otherwise uses  cov_canonical method mashr. Set as TRUE by default
#'
#' @return a list of mash objects
init_prior_mvfsusie <- function( tens_marg,indx_list, data.driven=TRUE)
{


  G_prior <- lapply(  1: (log2(sum( lengths(indx_lst)))+1) , function(s) fit_mash_level(marg_assoc, s, indx_lst, data.driven =data.driven))
  return(G_prior)
}

#' @title Access to list of the prior covariances
#'
#' @description Access to list of fitted covariance of a mash prior of a given scale
#'
#' @param G_prior prior generated by \code{init_prior_mvfsusie}
#'
#' @param s scale of interest
#'
#' @return a list of covariance matrices
get_scale_Ulist_G_prior <- function( G_prior,s)
{
  out <-  G_prior[[s]]$fitted_g$Ulist
  return( out)
}
