
#' @title Initialize the prior for multsusie method
#'
#' @description generate list of object corresponding to the parameters of the prior for analysis
#'
#' @param Y a list of functional phenotype, in which each element is matrix of size N by size J. The underlying algorithm uses wavelet which assume that J is of the form J^2. If J not a power of 2, susif internally remaps the data into grid of length 2^J
#'
#' @param X matrix of size n by p in
#'
#' @param list_indx_lst list of list generated by \code{\link{gen_wavelet_indx}} for the given level of resolution
#'
#' @return an object of the class "mult_prior"
#'
#' @importFrom ashr ash
#'
#' @export
init_prior_multsusie <- function(Y,X, v1 , list_indx_lst )
{

    G_prior <-lapply(1:length(Y),  function(k) susiF.alpha::init_prior( Y        = Y[[k]],
                                                                        X        = X,
                                                                        v1       = v1,
                                                                        prior    = "mixture_normal_per_scale",
                                                                        indx_lst = list_indx_lst[[k]]
                                                                       )
                    )

    attr(G_prior, "class") <- "mult_fsusie_prior"



  return(G_prior)

}
